services:
  zoo:
    image: zookeeper:3.4.9
    hostname: zoo
    mem_limit: 1024m
    ports:
      - "2181:2181"
    environment:
      KAFKA_HEAP_OPTS: "-Xms64M -Xmx512M"
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo:2888:3888
    volumes:
      - volZoo:/data
      - volZooLog:/datalog

  kafka:
    image: confluentinc/cp-kafka:4.0.3-1
    hostname: kafka
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://ISI_DENGAN_IP_LOKAL:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - volKafka1:/var/lib/kafka/data
    depends_on:
      - zoo
  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.0.3-1
    hostname: kafka-rest
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: "kafka-rest"
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:19092"
    depends_on:
      - kafka
volumes:
  volZoo:
    driver: local
  volZooLog:
    driver: local
  volKafka1:
    driver: local
