version: '2.4'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    mem_limit: 1024m
    ports:
      - "2181:2181"
    environment:
      KAFKA_HEAP_OPTS: "-Xms64M -Xmx512M"
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - volZoo:/data
      - volZooLog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:4.0.3-1
    hostname: kafka1
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://GANTI_DENGAN_IP_LOKAL:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - volKafka1:/var/lib/kafka/data
    depends_on:
      - zoo1
  kafka2:
    image: confluentinc/cp-kafka:4.0.3-1
    hostname: kafka2
    mem_limit: 1024m
    ports:
      - "9093:9093"
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://$GANTI_DENGAN_IP_LOKAL:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - volKafka2:/var/lib/kafka/data
    depends_on:
      - zoo1
  kafka3:
    image: confluentinc/cp-kafka:4.0.3-1
    hostname: kafka3
    mem_limit: 1024m
    ports:
      - "9094:9094"
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://GANTI_DENGAN_IP_LOCAL:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - volKafka3:/var/lib/kafka/data
    depends_on:
      - zoo1
  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.0.3-1
    hostname: kafka-rest
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: "kafka-rest"
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka1:19092,PLAINTEXT://kafka2:19092,PLAINTEXT://kafka3:19092"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
volumes:
  volZoo:
    driver: local
  volZooLog:
    driver: local
  volKafka1:
    driver: local
  volKafka2:
    driver: local
  volKafka3:
    driver: local
